name: Build exe file

on:
  push #:
#    tags:
#      - '0.1.1-alpha.1'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools pyinstaller

      - name: Build the exe file
        run: |
          pyinstaller --onefile yt_monk/yt_monk.py

      - name: List dist files
        run: |
          dir dist

      - name: Upload exe artifact
        uses: actions/upload-artifact@v3
        with:
          name: yt-monk-exe
          path: dist/yt_monk.exe  # Ensure this matches the actual name of the output file
