name: Build exe file

on:
  push #:
#    tags:
#      - '0.1.1-alpha.1'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools pyinstaller

      - name: Build the exe file
        run: |
          pyinstaller --onefile yt_monk/yt_monk.py

      - name: Commit and Push EXE to Repository
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/yt_monk.exe
          git commit -m "Add built EXE file"
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
